"""initial schema

Revision ID: b571072e66ea
Revises: 
Create Date: 2026-08-04 10:14:19.748535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b571072e66ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMINISTRATOR', 'PORT_OPERATOR', 'CUSTOMS_OFFICER', 'SECURITY_OFFICER', name='userrole'), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('log_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('imo_number', sa.String(length=20), nullable=False),
    sa.Column('port_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('DOCKED', 'EN_ROUTE', 'DEPARTING', name='shipstatus'), nullable=False),
    sa.Column('eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imo_number')
    )
    op.create_table('containers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('container_code', sa.String(length=24), nullable=False),
    sa.Column('ship_id', sa.String(length=36), nullable=True),
    sa.Column('origin_port_id', sa.String(length=36), nullable=True),
    sa.Column('destination_port_id', sa.String(length=36), nullable=True),
    sa.Column('current_lat', sa.Float(), nullable=False),
    sa.Column('current_lng', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('heading', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('MOVING', 'DELAYED', 'CLEARED', 'HIGH_RISK', 'IDLE', name='containerstatus'), nullable=False),
    sa.Column('cargo_type', sa.String(length=80), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['destination_port_id'], ['ports.id'], ),
    sa.ForeignKeyConstraint(['origin_port_id'], ['ports.id'], ),
    sa.ForeignKeyConstraint(['ship_id'], ['ships.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('container_code')
    )
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('container_id', sa.String(length=36), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anomalies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('container_id', sa.String(length=36), nullable=False),
    sa.Column('anomaly_type', sa.Enum('ROUTE_DEVIATION', 'GPS_SPOOFING', 'UNAUTHORIZED_STOP', 'DOOR_OPEN', 'IDLE_CONTAINER', 'TEMPERATURE_ANOMALY', name='anomalytype'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel'), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('container_id', sa.String(length=36), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('detected_objects', sa.JSON(), nullable=False),
    sa.Column('inspector_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PASSED', 'FLAGGED', name='inspectionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manifests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('container_id', sa.String(length=36), nullable=False),
    sa.Column('declared_goods', sa.String(length=255), nullable=False),
    sa.Column('declared_weight', sa.Float(), nullable=False),
    sa.Column('hs_code', sa.String(length=20), nullable=True),
    sa.Column('consignee', sa.String(length=160), nullable=True),
    sa.Column('consignor', sa.String(length=160), nullable=True),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('container_id', sa.String(length=36), nullable=False),
    sa.Column('gps_score', sa.Float(), nullable=False),
    sa.Column('rfid_score', sa.Float(), nullable=False),
    sa.Column('sensor_score', sa.Float(), nullable=False),
    sa.Column('manifest_score', sa.Float(), nullable=False),
    sa.Column('yolo_score', sa.Float(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel'), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('container_id', sa.String(length=36), nullable=False),
    sa.Column('waypoints', sa.JSON(), nullable=False),
    sa.Column('predicted_route', sa.JSON(), nullable=False),
    sa.Column('eta_actual', sa.DateTime(timezone=True), nullable=True),
    sa.Column('eta_predicted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delay_probability', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_readings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('container_id', sa.String(length=36), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('battery_level', sa.Float(), nullable=False),
    sa.Column('door_status', sa.Enum('CLOSED', 'OPEN', name='doorstatus'), nullable=False),
    sa.Column('movement_status', sa.Enum('MOVING', 'STATIONARY', name='movementstatus'), nullable=False),
    sa.Column('gps_valid', sa.Boolean(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clearances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('container_id', sa.String(length=36), nullable=False),
    sa.Column('risk_score_id', sa.String(length=36), nullable=True),
    sa.Column('officer_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='clearancestatus'), nullable=False),
    sa.Column('blockchain_hash', sa.String(length=128), nullable=True),
    sa.Column('transaction_id', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['risk_score_id'], ['risk_scores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shap_explanations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('risk_score_id', sa.String(length=36), nullable=False),
    sa.Column('feature_name', sa.String(length=80), nullable=False),
    sa.Column('contribution_value', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['risk_score_id'], ['risk_scores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shap_explanations')
    op.drop_table('clearances')
    op.drop_table('sensor_readings')
    op.drop_table('routes')
    op.drop_table('risk_scores')
    op.drop_table('manifests')
    op.drop_table('inspections')
    op.drop_table('anomalies')
    op.drop_table('alerts')
    op.drop_table('containers')
    op.drop_table('ships')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('ports')
    # ### end Alembic commands ###
