"""Cargo Inspection PDF report generator, built on reportlab (pure-Python,
no system dependencies — safe to add to a container image without extra
apt packages)."""

from datetime import datetime, timezone
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.models.container import Container
from app.models.inspection import Inspection
from app.models.user import User

THREAT_COLORS = {
    "none": colors.HexColor("#10B981"),
    "low": colors.HexColor("#10B981"),
    "medium": colors.HexColor("#F59E0B"),
    "high": colors.HexColor("#EF4444"),
    "critical": colors.HexColor("#991B1B"),
}


def _recommendation(inspection: Inspection) -> str:
    threat = inspection.threat_level.value
    if threat == "critical":
        return "Do not clear. Escalate to Security Team for immediate physical inspection."
    if threat == "high":
        return "Secondary inspection required before customs clearance is issued."
    if threat == "medium":
        return "Manual review recommended; hold pending customs officer sign-off."
    return "No restricted objects detected. Cleared to proceed through standard customs processing."


def build_inspection_report(
    inspection: Inspection,
    container: Container,
    inspector: User | None,
    output_path: Path,
) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "TwinTitle", parent=styles["Heading1"], fontSize=18, spaceAfter=2
    )
    subtitle_style = ParagraphStyle(
        "TwinSubtitle", parent=styles["Normal"], textColor=colors.HexColor("#64748B")
    )
    section_style = ParagraphStyle(
        "Section", parent=styles["Heading2"], fontSize=12, spaceBefore=14, spaceAfter=6
    )

    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
        title=f"Cargo Inspection Report — {container.container_code}",
    )

    story = [
        Paragraph("PortSynAI — Cargo Inspection Report", title_style),
        Paragraph(
            "AI-assisted X-ray screening summary generated by the YOLOv8 cargo inspection module.",
            subtitle_style,
        ),
        Spacer(1, 10 * mm),
    ]

    meta_rows = [
        ["Container ID", container.container_code],
        ["Cargo Type", container.cargo_type],
        ["Inspection Date", inspection.created_at.strftime("%Y-%m-%d %H:%M UTC")],
        ["Inspector", inspector.name if inspector else "Unassigned"],
        ["Inspection Status", inspection.status.value.title()],
        ["Overall Threat Level", inspection.threat_level.value.upper()],
        [
            "Processing Time",
            f"{inspection.processing_ms:.0f} ms" if inspection.processing_ms else "—",
        ],
    ]
    meta_table = Table(meta_rows, colWidths=[55 * mm, 105 * mm])
    meta_table.setStyle(
        TableStyle(
            [
                ("FONTSIZE", (0, 0), (-1, -1), 9.5),
                ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#334155")),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("LINEBELOW", (0, 0), (-1, -1), 0.4, colors.HexColor("#E2E8F0")),
            ]
        )
    )
    story.append(meta_table)

    story.append(Paragraph("Detected Objects", section_style))
    if not inspection.detected_objects:
        story.append(Paragraph("No objects were detected in this scan.", styles["Normal"]))
    else:
        header = ["Object", "Category", "Confidence", "Threat Level"]
        rows = [header]
        for obj in inspection.detected_objects:
            rows.append(
                [
                    obj.get("label", "—"),
                    obj.get("category", "—"),
                    f"{obj.get('confidence', 0) * 100:.1f}%",
                    obj.get("threat_level", "none").upper(),
                ]
            )
        detection_table = Table(rows, colWidths=[45 * mm, 40 * mm, 35 * mm, 40 * mm])
        style_commands = [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0A1628")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#E2E8F0")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F6F8FA")]),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]
        for i, obj in enumerate(inspection.detected_objects, start=1):
            threat_color = THREAT_COLORS.get(obj.get("threat_level", "none"), colors.black)
            style_commands.append(("TEXTCOLOR", (3, i), (3, i), threat_color))
            style_commands.append(("FONTNAME", (3, i), (3, i), "Helvetica-Bold"))
        detection_table.setStyle(TableStyle(style_commands))
        story.append(detection_table)

    story.append(Paragraph("Recommendation", section_style))
    story.append(Paragraph(_recommendation(inspection), styles["Normal"]))

    story.append(Spacer(1, 10 * mm))
    story.append(
        Paragraph(
            f"Report generated {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')} "
            "by PortSynAI. Detections produced by an automated YOLOv8 screening pipeline and "
            "should be confirmed by a customs officer before any enforcement action.",
            subtitle_style,
        )
    )

    doc.build(story)
    return output_path
